# Qbitel EdgeOS - Codecov configuration
# https://docs.codecov.io/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...95"

  status:
    project:
      default:
        target: 75%
        threshold: 2%
        if_ci_failed: error
      crypto:
        paths:
          - "crates/q-crypto/src/**"
        target: 85%
        threshold: 1%
      kernel:
        paths:
          - "crates/q-kernel/src/**"
        target: 80%
        threshold: 2%
      boot:
        paths:
          - "crates/q-boot/src/**"
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**"
  - "examples/**"
  - "tools/**"
  - "benches/**"
  - "docs/**"
